version: '3.1'

services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 10
    networks:
      - lb-express-docker
  lb:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/logs/:/var/log/nginx"
    networks:
      - lb-express-docker
    depends_on:
      - app

networks:
 lb-express-docker: